/**
 * Static mapping of Row Numbers in the Excel 'rawData' worksheet to their corresponding
 * Input Schema Parameter IDs (for single values) and Brix/Pol Chemical Analysis keys.
 */

export interface BrixPolConfig {
  brixKey: string;
  polKey: string;
}

export const EXCEL_ROW_SINGLE_VALUES: Record<number, string> = {
  3: 'plantStartDate',
  4: 'plantStartTime',
  5: 'plantShutdownDate',
  6: 'plantShutdownTime',
  7: 'cropDay',
  8: 'todayDate',
  9: 'rain',
  10: 'tempMax',
  11: 'tempMin',
  12: 'humidity',
  14: 'caneCrushed',
  15: 'gate',
  16: 'road',
  17: 'closingBal',
  18: 'earlyVariety',
  19: 'totalCaneCrushed',
  20: 'divertedSyrup',
  21: 'molassesSentOut',
  22: 'imbibition',
  23: 'dirtPercent',
  24: 'filterCakeProduction',
  25: 'grossMixedJuice',
  26: 'l31S',
  27: 'm31S',
  28: 's31S',
  29: 'l31',
  30: 'm31',
  31: 's31',
  32: 'sSs31Export',
  33: 'rawSugar',
  34: 'llBold',
  35: 'brownSugar',
  36: 'totalSugarBagged',
  38: 'reprocessBrownSugar',
  39: 'reprocessRawSugar',
  41: 'lime',
  42: 'sulphur',
  43: 'ppBags',
  44: 'millSanitationChemicals',
  45: 'lubricants',
  46: 'grease',
  47: 'phosphoricAcid',
  48: 'colourPrecipitant',
  50: 'aMassecuite',
  51: 'a1Massecuite',
  52: 'bMassecuite',
  53: 'b1Massecuite',
  54: 'cMassecuite',
  55: 'r1Massecuite',
  56: 'r3Massecuite',
  57: 'totalMassecuite',
  59: 'stopNoCane',
  60: 'stopMechanical',
  61: 'stopElectrical',
  62: 'stopInstrumentation',
  63: 'stopProcess',
  64: 'stopGenCleaning',
  65: 'stopMiscellaneous',
  66: 'totalHoursLost',
  68: 'sugarColourGs10',
  69: 'sugarColourGs8',
  70: 'sugarReflectance',
  71: 'moisture',
  72: 'particleSizeMa',
  73: 'particleSizeCv',
  75: 'powerGeneration',
  76: 'powerExport',
  77: 'powerImport',
  78: 'powerConsumption',
  80: 'rawWaterConsumption',
  81: 'treatedWaterDischarge',
  82: 'treatedWaterRecycled',
  83: 'dmWaterConsumption',
  84: 'steamGeneration',
  85: 'steamFuelRatio',
  86: 'boilingHouseSteamConsumption',
  121: 'sentOutMolassesTrs',
  122: 'divertedSyrupTrs',
};

export const EXCEL_ROW_BRIX_POL: Record<number, BrixPolConfig> = {
  88: { brixKey: 'primaryJuiceBrix', polKey: 'primaryJuicePol' },
  89: { brixKey: 'mixedJuiceBrix', polKey: 'mixedJuicePol' },
  90: { brixKey: 'lastMillJuiceBrix', polKey: 'lastMillJuicePol' },
  91: { brixKey: 'clearJuiceBrix', polKey: 'clearJuicePol' },
  92: { brixKey: 'divertedSyrupBrix', polKey: 'divertedSyrupPol' },
  93: { brixKey: 'unsulphuredSyrupBrix', polKey: 'unsulphuredSyrupPol' },
  94: { brixKey: 'sulphuredSyrupBrix', polKey: 'sulphuredSyrupPol' },
  95: { brixKey: 'filterJuiceBrix', polKey: 'filterJuicePol' },
  96: { brixKey: 'bagassePol', polKey: 'bagasseBrix' },
  97: { brixKey: 'filterCakePol', polKey: 'filterCakeBrix' },
  98: { brixKey: 'aMassecuiteBrix', polKey: 'aMassecuitePol' },
  99: { brixKey: 'a1MassecuiteBrix', polKey: 'a1MassecuitePol' },
  100: { brixKey: 'bMassecuiteBrix', polKey: 'bMassecuitePol' },
  101: { brixKey: 'b1MassecuiteBrix', polKey: 'b1MassecuitePol' },
  102: { brixKey: 'cMassecuiteBrix', polKey: 'cMassecuitePol' },
  103: { brixKey: 'aHeavyMolassesBrix', polKey: 'aHeavyMolassesPol' },
  104: { brixKey: 'aLightMolassesBrix', polKey: 'aLightMolassesPol' },
  105: { brixKey: 'a1HeavyMolassesBrix', polKey: 'a1HeavyMolassesPol' },
  106: { brixKey: 'bHeavyMolassesBrix', polKey: 'bHeavyMolassesPol' },
  107: { brixKey: 'b1HeavyMolassesBrix', polKey: 'b1HeavyMolassesPol' },
  108: { brixKey: 'cLightMolassesBrix', polKey: 'cLightMolassesPol' },
  109: { brixKey: 'finalMolassesBrix', polKey: 'finalMolassesPol' },
  110: { brixKey: 'bCuredSugarBrix', polKey: 'bCuredSugarPol' },
  111: { brixKey: 'cSingleCuredBrix', polKey: 'cSingleCuredPol' },
  112: { brixKey: 'cDoubleCuredBrix', polKey: 'cDoubleCuredPol' },
  113: { brixKey: 'magmaBrix', polKey: 'magmaPol' },
  114: { brixKey: 'meltBrix', polKey: 'meltPol' },
  115: { brixKey: 'rawMeltBrix', polKey: 'rawMeltPol' },
  116: { brixKey: 'refinedSyrupBrix', polKey: 'refinedSyrupPol' },
  117: { brixKey: 'r1MassecuiteBrix', polKey: 'r1MassecuitePol' },
  118: { brixKey: 'r1MolassesBrix', polKey: 'r1MolassesPol' },
  119: { brixKey: 'r3MassecuiteBrix', polKey: 'r3MassecuitePol' },
  120: { brixKey: 'r3MolassesBrix', polKey: 'r3MolassesPol' },
};
